# Generated by Django 2.2.2 on 2020-07-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Late_name',
            new_name='Last_name',
        ),
    ]
